import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Iroh",
  description: "Terms and conditions for using the Iroh legal research platform.",
};

export default function TermsOfService() {
  return (
    <>
      <nav className="border-b border-dark/5 py-4 px-6">
        <div className="max-w-3xl mx-auto">
          <Link href="/" className="font-serif text-xl font-semibold">
            Iroh
          </Link>
        </div>
      </nav>
      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="font-serif text-4xl font-semibold mb-2">
          Terms of Service
        </h1>
        <p className="text-dark/50 mb-12">Effective: 14 May 2026</p>

        <div className="prose prose-neutral max-w-none space-y-8 text-dark/80 leading-relaxed">
          <section>
            <h2 className="font-serif text-xl font-semibold text-dark mb-3">
              1. Acceptance of terms
            </h2>
            <p>
              By accessing or using Iroh (&ldquo;the Service&rdquo;), operated
              by Algedi Intelligence Labs Ltd (&ldquo;we&rdquo;, &ldquo;us&rdquo;,
              &ldquo;our&rdquo;), you agree to be bound by these Terms of
              Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-dark mb-3">
              2. Description of service
            </h2>
            <p>
              Iroh is an AI-powered legal research platform that enables users to
              search legislation, case law, and legal procedure across African
              jurisdictions. The Service provides research assistance and
              document retrieval with source citations.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-dark mb-3">
              3. Important disclaimer — not legal advice
            </h2>
            <p className="font-semibold">
              Iroh is not a law firm and does not provide legal advice.
            </p>
            <p className="mt-2">
              The information provided through the Service is for general
              research and informational purposes only. It does not constitute
              legal advice, and no advocate-client relationship is created by
              your use of Iroh. Responses generated by the Service may contain
              errors, omissions, or outdated information.
            </p>
            <p className="mt-2">
              You should always verify information independently and consult a
              qualified advocate admitted to practice in the relevant
              jurisdiction before taking any legal action based on information
              obtained through Iroh.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-dark mb-3">
              4. Permitted use
            </h2>
            <p>You may use the Service for:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>Legal research and reference purposes.</li>
              <li>Academic study and legal education.</li>
              <li>Professional legal work as a supplementary research tool.</li>
            </ul>
            <p className="mt-3">You may <strong>not</strong>:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>
                Scrape, crawl, or systematically extract data from the Service.
              </li>
              <li>
                Resell, sublicense, or redistribute Service outputs commercially
                without our written consent.
              </li>
              <li>
                Use the Service to generate spam, misleading legal documents, or
                for any unlawful purpose.
              </li>
              <li>
                Attempt to reverse-engineer, decompile, or access the underlying
                systems of the Service.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-dark mb-3">
              5. User accounts and security
            </h2>
            <p>
              You are responsible for maintaining the confidentiality of your
              account credentials and for all activity under your account. You
              must notify us immediately at{" "}
              <a
                href="mailto:david@makini.tech"
                className="text-gold hover:underline"
              >
                david@makini.tech
              </a>{" "}
              if you suspect unauthorised access to your account.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-dark mb-3">
              6. Intellectual property
            </h2>
            <p>
              The Service, including its design, code, legal corpus curation, and
              AI models configuration, is the intellectual property of Algedi
              Intelligence Labs Ltd or its licensors.
            </p>
            <p className="mt-2">
              You retain ownership of the queries you submit and any original
              work product you create using the Service as a tool. Legislation
              and case law cited in responses remain in the public domain as
              published by their respective governments.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-dark mb-3">
              7. Limitation of liability
            </h2>
            <p>
              To the maximum extent permitted by Kenyan law, Algedi Intelligence
              Labs Ltd shall not be liable for any indirect, incidental, special,
              consequential, or punitive damages arising out of or related to
              your use of the Service, including but not limited to:
            </p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>Reliance on information provided by the Service.</li>
              <li>
                Errors, inaccuracies, or omissions in research results or
                citations.
              </li>
              <li>Service interruptions or data loss.</li>
              <li>
                Any legal outcomes resulting from decisions made using information
                from the Service.
              </li>
            </ul>
            <p className="mt-3">
              Our total aggregate liability shall not exceed the amount you paid
              to us in the twelve (12) months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-dark mb-3">
              8. Governing law and dispute resolution
            </h2>
            <p>
              These Terms shall be governed by and construed in accordance with
              the laws of the Republic of Kenya. Any disputes arising out of or
              in connection with these Terms shall be subject to the exclusive
              jurisdiction of the courts of Nairobi, Kenya.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-dark mb-3">
              9. Changes to these terms
            </h2>
            <p>
              We reserve the right to modify these Terms at any time. Material
              changes will be communicated via email or notice on the platform at
              least 14 days before they take effect. Continued use of the Service
              after changes constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-dark mb-3">
              10. Contact
            </h2>
            <p>
              For questions about these Terms of Service, contact:
            </p>
            <p className="mt-2">
              Algedi Intelligence Labs Ltd
              <br />
              Email:{" "}
              <a
                href="mailto:david@makini.tech"
                className="text-gold hover:underline"
              >
                david@makini.tech
              </a>
              <br />
              Nairobi, Kenya
            </p>
          </section>
        </div>
      </main>
    </>
  );
}
